# This file is used by Travis CI to handle the continuous integration. It's expected that the CI
# server will check compilation and unit tests.
# 
# Currently a convulted mess because the default simple SBT command that Travis CI is supposed to
# support aren't working. This is a workaround from
# <https://gist.github.com/joscha/82cf74a6535407a43668>. It downloads the appropriate version of
# activator and runs it.
language: scala
script: "cd $TRAVIS_BUILD_DIR && ./activator test"
# Notify on build failure. We notify only when the success status changes. So if the build was
# succeeding and suddenly fails, we notify. If the build was failing and now succeeds, we notify.
# The reason to notify on change is so that if multiple people are trying to resolve a failure,
# they'll know if someone else succeeded and won't waste time continuing.
#notifications:
#  email:
#    recipients:
#      - m.l.hoffert@gmail.com # Mike
#      - kjamieson098@gmail.com # Katherine
#      - annduanlujie@gmail.com # Lujie
#      - danielblanche54@gmail.com # Daniel
#      - Lys.jordan@gmail.com # Jordan
#      - quentinjayp@gmail.com # Quentin
#      - Magnusandy@gmail.com # Andrew
#      - ejl389@mail.usask.ca # Erik
#    on_success: change
#    on_failure: change